In [1]:
import sys
import cv2
import numpy as np
import tensorflow as tf

sys.path.append("/home/hoheon/Jupyter/2021/ppedge/ppedge")
img = cv2.imread("/home/hoheon/Jupyter/2021/ppedge/example_dataset/statefarm/c0/img_34.jpg")

from models import build_model
from profiler import Profiler

In [27]:
import matplotlib.pyplot as plt

plt.imshow(img.mean(axis=-1, keepdims=True), cmap="gray")

In [2]:
model = build_model()

In [3]:
img_tensor = tf.convert_to_tensor(img[np.newaxis], dtype=tf.float32)

In [4]:
model(img_tensor)

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.02101101, 0.00847282, 1.        , 0.9965012 , 0.00217159,
        0.00172391, 0.01512186, 0.15315974, 0.5370331 , 0.99963355]],
      dtype=float32)>

In [5]:
profiler = Profiler(model, "block5_conv4")

In [7]:
result_tensor=profiler.feed_forward_subgraph(img, 5)

In [8]:
result_tensor

<tf.Tensor: shape=(1, 479, 639, 64), dtype=float32, numpy=
array([[[[4.26884705e+02, 4.56233101e+01, 0.00000000e+00, ...,
          4.09617958e+01, 3.99687958e+02, 7.68733139e+01],
         [4.64510155e+01, 1.29175385e+02, 1.61644135e+01, ...,
          9.62427673e+01, 1.16439323e+02, 6.27579403e+00],
         [9.01690826e+01, 1.10094360e+02, 0.00000000e+00, ...,
          8.05987320e+01, 4.01466217e+01, 0.00000000e+00],
         ...,
         [2.57400726e+02, 0.00000000e+00, 1.62921432e+02, ...,
          4.94253120e+01, 0.00000000e+00, 1.05683545e+03],
         [1.40153491e+03, 2.09556351e+02, 1.78921417e+02, ...,
          7.64898300e+01, 0.00000000e+00, 1.42894836e+03],
         [4.45595520e+02, 2.52031754e+02, 9.04178467e+01, ...,
          9.83221893e+01, 0.00000000e+00, 8.67628479e+02]],

        [[1.10068985e+02, 8.11846848e+01, 3.25538940e+01, ...,
          9.07106934e+01, 3.93484955e+02, 0.00000000e+00],
         [0.00000000e+00, 1.11495239e+02, 1.46763168e+02, ...,
        